# Generated by Django 5.2.9 on 2026-01-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_trade_emotion_trade_is_backtest_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_reason',
            field=models.TextField(blank=True, help_text='Why did you take this trade position?'),
        ),
    ]
